[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_counter = "Gz9MyXRttiXTVGZFqGLWh25x1N65mKVBRmnV4bBLi9g3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jozark/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
